pipeline {
agent any

environment {
    BACKEND_IMAGE = "backend-app"
    FRONTEND_IMAGE = "frontend-app"
    TAG = "${BUILD_NUMBER}"
    NETWORK = "devops-net"
}

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Build Backend Image') {
        steps {
            bat 'docker build -t %BACKEND_IMAGE%:%TAG% -f projects/docker_e2e_proj/docker/Dockerfile.backend .'
        }
    }

    stage('Build Frontend Image') {
        steps {
            bat 'docker build -t %FRONTEND_IMAGE%:%TAG% -f projects/docker_e2e_proj/docker/Dockerfile.frontend .'
        }
    }

    stage('Create Network') {
        steps {
            bat 'docker network create %NETWORK% || exit 0'
        }
    }

    stage('Run Backend') {
        steps {
            bat '''
            docker rm -f backend || exit 0
            docker run -d --name backend --network %NETWORK% %BACKEND_IMAGE%:%TAG%
            '''
        }
    }

    stage('Run Frontend') {
        steps {
            bat '''
            docker rm -f frontend || exit 0
            docker run -d -p 8086:80 --name frontend --network %NETWORK% %FRONTEND_IMAGE%:%TAG%
            '''
        }
    }

    stage('Test Application') {
        steps {
            bat 'curl http://localhost:8086'
        }
    }
}

post {
    success {
        echo "SUCCESS: Full-stack app deployed"
    }
    failure {
        echo "FAILURE: Check logs"
    }
}
}

