// my docker file

// pipeline {
//     agent any
//     environment {
//         IMAGE_NAME = "my-nginx-app"
//         IMAGE_TAG = "${BUILD_NUMBER}"
//     }
//     stages {
//         stage('Checkout') {
//             steps {
//                 checkout scm
//             }
//         }
//         stage('Build Docker Image') {
//             steps {
//                 sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG -f projects/docker/docker/Dockerfile .'
//             }
//         }
//         stage('Run Container') {
//             steps {
//                 sh '''
//                 docker stop my-container || true
//                 docker rm my-container || true
//                 docker run -d -p 8083:80 --name my-container $IMAGE_NAME
//                 '''
//             }
//         }
//         stage('Test UI') {
//             steps {
//                 sh 'curl -f http://localhost:8083'
//             }
//         }
//     }
//     post {
//         success {
//             echo "✅ Deployment Successful"
//         }
//         failure {
//             echo "❌ Deployment Failed"
//         }
//         always {
//             echo "Pipeline Finished"
//         }
//     }
// }

pipeline {
agent any
environment {
    IMAGE_NAME = "my-nginx-app"
    DOCKERHUB_USER = "hariprasad8452"
    IMAGE_TAG = "${BUILD_NUMBER}"
    FULL_IMAGE = "%DOCKERHUB_USER%/%IMAGE_NAME%:%IMAGE_TAG%"
}
stages {
    stage('Checkout') {
        steps {
            checkout scm
        }
    }
    stage('Build Image') {
        steps {
            bat 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% -f projects/docker/docker/Dockerfile .'
        }
    }
    stage('Tag Image') {
        steps {
            bat 'docker tag %IMAGE_NAME%:%IMAGE_TAG% %DOCKERHUB_USER%/%IMAGE_NAME%:%IMAGE_TAG%'
        }
    }
    stage('Push to DockerHub') {
        steps {
            bat 'docker push %DOCKERHUB_USER%/%IMAGE_NAME%:%IMAGE_TAG%'
        }
    }
    stage('Clean Local Container') {
        steps {
            bat 'docker rm -f deploy-container || exit 0'
        }
    }
    stage('Pull from DockerHub') {
        steps {
            bat 'docker pull %DOCKERHUB_USER%/%IMAGE_NAME%:%IMAGE_TAG%'
        }
    }
    stage('Run on 8084') {
        steps {
            bat '''
            docker run -d -p 8084:80 --name deploy-container %DOCKERHUB_USER%/%IMAGE_NAME%:%IMAGE_TAG%
            '''
        }
    }
    stage('Test UI') {
        steps {
            bat 'curl http://localhost:8084'
        }
    }
}
post {
    success {
        echo "SUCCESS: Image built, pushed, pulled, and deployed"
    }
    failure {
        echo "FAILURE: Check logs"
    }
}
}
