pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t hariprasad8452/portfolio-backend:latest projects/fsd_k8s/backend'
                sh 'docker build -t hariprasad8452/portfolio-frontend:latest projects/fsd_k8s/frontend'
            }
        }
        stage('Push') {
            steps {
                // You must add 'docker-hub-creds' in Jenkins Credentials
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh "docker login -u $USER -p $PASS"
                    sh "docker push hariprasad8452/portfolio-backend:latest"
                    sh "docker push hariprasad8452/portfolio-frontend:latest"
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG')]) {
                    sh "kubectl apply -f projects/fsd_k8s/k8s-spec.yaml"
                    sh "kubectl rollout restart deployment/frontend-deploy"
                    sh "kubectl rollout restart deployment/backend-deploy"
                }
            }
        }
    }
}
