# Stage 1 (builder)
FROM python:3.9-slim AS builder

WORKDIR /app

COPY projects/docker_e2e_proj/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2 (final)
FROM python:3.9-alpine

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.9 /usr/local/lib/python3.9

COPY projects/docker_e2e_proj/backend .

EXPOSE 5000

CMD ["python", "app.py"]
